### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-html-more-kinds-of-content-OSB7Pe#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://harr1193.github.io/MI-449-SS17-741-html-more-kinds-of-content-OSB7Pe/) and meets the following criteria:

- [x] Include [a haiku](http://www.kidzone.ws/poetry/haiku.htm), describing the feelings this product will evoke (with `br` elements to add new lines where appropriate)
- [x] [Create and download a sound effect file](http://sfbgames.com/chiptone/) for what the game will sound like when you win, then include an audio player in the page so users can hear the sample
- [x] Include a table comparing which features your game has in comparison to competitors (these competitors may be real or made up)
- [x] Include a demo video from YouTube, but featuring a completely unrelated animal being cute (not getting hurt!)

**Comment by chrisvfritz** [comment]
Wow, I like to always find _some_ room for improvement, but this code is... flawless. 💎 

_Very_ well done! Magnificent attention to detail! 🎉 :shipit: 🚀 

Did you have any related questions I could answer? Any additional resources I could point you to? I feel like I haven't done enough this round to help you build your skills. 😅
